//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoFinanciera.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Indicadores
    {
        public int Id { get; set; }
        public int COD_INDICADORINTERNO { get; set; }
        public System.DateTime DES_FECHA { get; set; }
        public decimal NUM_VALOR { get; set; }
    }


}
